server:
  port: 8080
# config spring framework
spring:
# config h2 db, store to file ./data/demo
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    console.settings.web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123456
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
# custom handler not found resource of spring => throw exception then custom by Controller Advice
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
# config swagger path
springdoc:
  api-docs:
    path: /swagger-ui.html
# config log level
logging:
  level:
    com:
      sotatek: DEBUG
    org:
      springframework: INFO
management:
  security:
    enabled: false

